// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/compiler/profile.proto

#ifndef PROTOBUF_INCLUDED_google_2fprotobuf_2fcompiler_2fprofile_2eproto
#define PROTOBUF_INCLUDED_google_2fprotobuf_2fcompiler_2fprofile_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_google_2fprotobuf_2fcompiler_2fprofile_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_google_2fprotobuf_2fcompiler_2fprofile_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_google_2fprotobuf_2fcompiler_2fprofile_2eproto();
namespace google {
namespace protobuf {
namespace compiler {
class AccessInfo;
class AccessInfoDefaultTypeInternal;
extern AccessInfoDefaultTypeInternal _AccessInfo_default_instance_;
class FieldAccessInfo;
class FieldAccessInfoDefaultTypeInternal;
extern FieldAccessInfoDefaultTypeInternal _FieldAccessInfo_default_instance_;
class MessageAccessInfo;
class MessageAccessInfoDefaultTypeInternal;
extern MessageAccessInfoDefaultTypeInternal _MessageAccessInfo_default_instance_;
}  // namespace compiler
template<> ::google::protobuf::compiler::AccessInfo* Arena::CreateMaybeMessage<::google::protobuf::compiler::AccessInfo>(Arena*);
template<> ::google::protobuf::compiler::FieldAccessInfo* Arena::CreateMaybeMessage<::google::protobuf::compiler::FieldAccessInfo>(Arena*);
template<> ::google::protobuf::compiler::MessageAccessInfo* Arena::CreateMaybeMessage<::google::protobuf::compiler::MessageAccessInfo>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace google {
namespace protobuf {
namespace compiler {

// ===================================================================

class FieldAccessInfo final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.protobuf.compiler.FieldAccessInfo) */ {
 public:
  FieldAccessInfo();
  virtual ~FieldAccessInfo();

  FieldAccessInfo(const FieldAccessInfo& from);

  inline FieldAccessInfo& operator=(const FieldAccessInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FieldAccessInfo(FieldAccessInfo&& from) noexcept
    : FieldAccessInfo() {
    *this = ::std::move(from);
  }

  inline FieldAccessInfo& operator=(FieldAccessInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const FieldAccessInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FieldAccessInfo* internal_default_instance() {
    return reinterpret_cast<const FieldAccessInfo*>(
               &_FieldAccessInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(FieldAccessInfo* other);
  friend void swap(FieldAccessInfo& a, FieldAccessInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FieldAccessInfo* New() const final {
    return CreateMaybeMessage<FieldAccessInfo>(nullptr);
  }

  FieldAccessInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<FieldAccessInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const FieldAccessInfo& from);
  void MergeFrom(const FieldAccessInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FieldAccessInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional uint64 getters_count = 2;
  bool has_getters_count() const;
  void clear_getters_count();
  static const int kGettersCountFieldNumber = 2;
  ::google::protobuf::uint64 getters_count() const;
  void set_getters_count(::google::protobuf::uint64 value);

  // optional uint64 setters_count = 3;
  bool has_setters_count() const;
  void clear_setters_count();
  static const int kSettersCountFieldNumber = 3;
  ::google::protobuf::uint64 setters_count() const;
  void set_setters_count(::google::protobuf::uint64 value);

  // optional uint64 configs_count = 4;
  bool has_configs_count() const;
  void clear_configs_count();
  static const int kConfigsCountFieldNumber = 4;
  ::google::protobuf::uint64 configs_count() const;
  void set_configs_count(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:google.protobuf.compiler.FieldAccessInfo)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::uint64 getters_count_;
  ::google::protobuf::uint64 setters_count_;
  ::google::protobuf::uint64 configs_count_;
  friend struct ::TableStruct_google_2fprotobuf_2fcompiler_2fprofile_2eproto;
};
// -------------------------------------------------------------------

class MessageAccessInfo final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.protobuf.compiler.MessageAccessInfo) */ {
 public:
  MessageAccessInfo();
  virtual ~MessageAccessInfo();

  MessageAccessInfo(const MessageAccessInfo& from);

  inline MessageAccessInfo& operator=(const MessageAccessInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MessageAccessInfo(MessageAccessInfo&& from) noexcept
    : MessageAccessInfo() {
    *this = ::std::move(from);
  }

  inline MessageAccessInfo& operator=(MessageAccessInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const MessageAccessInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MessageAccessInfo* internal_default_instance() {
    return reinterpret_cast<const MessageAccessInfo*>(
               &_MessageAccessInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(MessageAccessInfo* other);
  friend void swap(MessageAccessInfo& a, MessageAccessInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MessageAccessInfo* New() const final {
    return CreateMaybeMessage<MessageAccessInfo>(nullptr);
  }

  MessageAccessInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MessageAccessInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MessageAccessInfo& from);
  void MergeFrom(const MessageAccessInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MessageAccessInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .google.protobuf.compiler.FieldAccessInfo field = 3;
  int field_size() const;
  void clear_field();
  static const int kFieldFieldNumber = 3;
  ::google::protobuf::compiler::FieldAccessInfo* mutable_field(int index);
  ::google::protobuf::RepeatedPtrField< ::google::protobuf::compiler::FieldAccessInfo >*
      mutable_field();
  const ::google::protobuf::compiler::FieldAccessInfo& field(int index) const;
  ::google::protobuf::compiler::FieldAccessInfo* add_field();
  const ::google::protobuf::RepeatedPtrField< ::google::protobuf::compiler::FieldAccessInfo >&
      field() const;

  // optional string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional uint64 count = 2;
  bool has_count() const;
  void clear_count();
  static const int kCountFieldNumber = 2;
  ::google::protobuf::uint64 count() const;
  void set_count(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:google.protobuf.compiler.MessageAccessInfo)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::google::protobuf::compiler::FieldAccessInfo > field_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::uint64 count_;
  friend struct ::TableStruct_google_2fprotobuf_2fcompiler_2fprofile_2eproto;
};
// -------------------------------------------------------------------

class AccessInfo final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.protobuf.compiler.AccessInfo) */ {
 public:
  AccessInfo();
  virtual ~AccessInfo();

  AccessInfo(const AccessInfo& from);

  inline AccessInfo& operator=(const AccessInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AccessInfo(AccessInfo&& from) noexcept
    : AccessInfo() {
    *this = ::std::move(from);
  }

  inline AccessInfo& operator=(AccessInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const AccessInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AccessInfo* internal_default_instance() {
    return reinterpret_cast<const AccessInfo*>(
               &_AccessInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(AccessInfo* other);
  friend void swap(AccessInfo& a, AccessInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AccessInfo* New() const final {
    return CreateMaybeMessage<AccessInfo>(nullptr);
  }

  AccessInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AccessInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AccessInfo& from);
  void MergeFrom(const AccessInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AccessInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .google.protobuf.compiler.MessageAccessInfo message = 1;
  int message_size() const;
  void clear_message();
  static const int kMessageFieldNumber = 1;
  ::google::protobuf::compiler::MessageAccessInfo* mutable_message(int index);
  ::google::protobuf::RepeatedPtrField< ::google::protobuf::compiler::MessageAccessInfo >*
      mutable_message();
  const ::google::protobuf::compiler::MessageAccessInfo& message(int index) const;
  ::google::protobuf::compiler::MessageAccessInfo* add_message();
  const ::google::protobuf::RepeatedPtrField< ::google::protobuf::compiler::MessageAccessInfo >&
      message() const;

  // @@protoc_insertion_point(class_scope:google.protobuf.compiler.AccessInfo)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::google::protobuf::compiler::MessageAccessInfo > message_;
  friend struct ::TableStruct_google_2fprotobuf_2fcompiler_2fprofile_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FieldAccessInfo

// optional string name = 1;
inline bool FieldAccessInfo::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FieldAccessInfo::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& FieldAccessInfo::name() const {
  // @@protoc_insertion_point(field_get:google.protobuf.compiler.FieldAccessInfo.name)
  return name_.GetNoArena();
}
inline void FieldAccessInfo::set_name(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.compiler.FieldAccessInfo.name)
}
#if LANG_CXX11
inline void FieldAccessInfo::set_name(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.protobuf.compiler.FieldAccessInfo.name)
}
#endif
inline void FieldAccessInfo::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.compiler.FieldAccessInfo.name)
}
inline void FieldAccessInfo::set_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.compiler.FieldAccessInfo.name)
}
inline ::std::string* FieldAccessInfo::mutable_name() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:google.protobuf.compiler.FieldAccessInfo.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FieldAccessInfo::release_name() {
  // @@protoc_insertion_point(field_release:google.protobuf.compiler.FieldAccessInfo.name)
  if (!has_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FieldAccessInfo::set_allocated_name(::std::string* name) {
  if (name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.compiler.FieldAccessInfo.name)
}

// optional uint64 getters_count = 2;
inline bool FieldAccessInfo::has_getters_count() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FieldAccessInfo::clear_getters_count() {
  getters_count_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::uint64 FieldAccessInfo::getters_count() const {
  // @@protoc_insertion_point(field_get:google.protobuf.compiler.FieldAccessInfo.getters_count)
  return getters_count_;
}
inline void FieldAccessInfo::set_getters_count(::google::protobuf::uint64 value) {
  _has_bits_[0] |= 0x00000002u;
  getters_count_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.compiler.FieldAccessInfo.getters_count)
}

// optional uint64 setters_count = 3;
inline bool FieldAccessInfo::has_setters_count() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void FieldAccessInfo::clear_setters_count() {
  setters_count_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::uint64 FieldAccessInfo::setters_count() const {
  // @@protoc_insertion_point(field_get:google.protobuf.compiler.FieldAccessInfo.setters_count)
  return setters_count_;
}
inline void FieldAccessInfo::set_setters_count(::google::protobuf::uint64 value) {
  _has_bits_[0] |= 0x00000004u;
  setters_count_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.compiler.FieldAccessInfo.setters_count)
}

// optional uint64 configs_count = 4;
inline bool FieldAccessInfo::has_configs_count() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void FieldAccessInfo::clear_configs_count() {
  configs_count_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000008u;
}
inline ::google::protobuf::uint64 FieldAccessInfo::configs_count() const {
  // @@protoc_insertion_point(field_get:google.protobuf.compiler.FieldAccessInfo.configs_count)
  return configs_count_;
}
inline void FieldAccessInfo::set_configs_count(::google::protobuf::uint64 value) {
  _has_bits_[0] |= 0x00000008u;
  configs_count_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.compiler.FieldAccessInfo.configs_count)
}

// -------------------------------------------------------------------

// MessageAccessInfo

// optional string name = 1;
inline bool MessageAccessInfo::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageAccessInfo::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& MessageAccessInfo::name() const {
  // @@protoc_insertion_point(field_get:google.protobuf.compiler.MessageAccessInfo.name)
  return name_.GetNoArena();
}
inline void MessageAccessInfo::set_name(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.compiler.MessageAccessInfo.name)
}
#if LANG_CXX11
inline void MessageAccessInfo::set_name(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.protobuf.compiler.MessageAccessInfo.name)
}
#endif
inline void MessageAccessInfo::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.compiler.MessageAccessInfo.name)
}
inline void MessageAccessInfo::set_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.compiler.MessageAccessInfo.name)
}
inline ::std::string* MessageAccessInfo::mutable_name() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:google.protobuf.compiler.MessageAccessInfo.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MessageAccessInfo::release_name() {
  // @@protoc_insertion_point(field_release:google.protobuf.compiler.MessageAccessInfo.name)
  if (!has_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MessageAccessInfo::set_allocated_name(::std::string* name) {
  if (name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.compiler.MessageAccessInfo.name)
}

// optional uint64 count = 2;
inline bool MessageAccessInfo::has_count() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageAccessInfo::clear_count() {
  count_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::uint64 MessageAccessInfo::count() const {
  // @@protoc_insertion_point(field_get:google.protobuf.compiler.MessageAccessInfo.count)
  return count_;
}
inline void MessageAccessInfo::set_count(::google::protobuf::uint64 value) {
  _has_bits_[0] |= 0x00000002u;
  count_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.compiler.MessageAccessInfo.count)
}

// repeated .google.protobuf.compiler.FieldAccessInfo field = 3;
inline int MessageAccessInfo::field_size() const {
  return field_.size();
}
inline void MessageAccessInfo::clear_field() {
  field_.Clear();
}
inline ::google::protobuf::compiler::FieldAccessInfo* MessageAccessInfo::mutable_field(int index) {
  // @@protoc_insertion_point(field_mutable:google.protobuf.compiler.MessageAccessInfo.field)
  return field_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::google::protobuf::compiler::FieldAccessInfo >*
MessageAccessInfo::mutable_field() {
  // @@protoc_insertion_point(field_mutable_list:google.protobuf.compiler.MessageAccessInfo.field)
  return &field_;
}
inline const ::google::protobuf::compiler::FieldAccessInfo& MessageAccessInfo::field(int index) const {
  // @@protoc_insertion_point(field_get:google.protobuf.compiler.MessageAccessInfo.field)
  return field_.Get(index);
}
inline ::google::protobuf::compiler::FieldAccessInfo* MessageAccessInfo::add_field() {
  // @@protoc_insertion_point(field_add:google.protobuf.compiler.MessageAccessInfo.field)
  return field_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::google::protobuf::compiler::FieldAccessInfo >&
MessageAccessInfo::field() const {
  // @@protoc_insertion_point(field_list:google.protobuf.compiler.MessageAccessInfo.field)
  return field_;
}

// -------------------------------------------------------------------

// AccessInfo

// repeated .google.protobuf.compiler.MessageAccessInfo message = 1;
inline int AccessInfo::message_size() const {
  return message_.size();
}
inline void AccessInfo::clear_message() {
  message_.Clear();
}
inline ::google::protobuf::compiler::MessageAccessInfo* AccessInfo::mutable_message(int index) {
  // @@protoc_insertion_point(field_mutable:google.protobuf.compiler.AccessInfo.message)
  return message_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::google::protobuf::compiler::MessageAccessInfo >*
AccessInfo::mutable_message() {
  // @@protoc_insertion_point(field_mutable_list:google.protobuf.compiler.AccessInfo.message)
  return &message_;
}
inline const ::google::protobuf::compiler::MessageAccessInfo& AccessInfo::message(int index) const {
  // @@protoc_insertion_point(field_get:google.protobuf.compiler.AccessInfo.message)
  return message_.Get(index);
}
inline ::google::protobuf::compiler::MessageAccessInfo* AccessInfo::add_message() {
  // @@protoc_insertion_point(field_add:google.protobuf.compiler.AccessInfo.message)
  return message_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::google::protobuf::compiler::MessageAccessInfo >&
AccessInfo::message() const {
  // @@protoc_insertion_point(field_list:google.protobuf.compiler.AccessInfo.message)
  return message_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace compiler
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_google_2fprotobuf_2fcompiler_2fprofile_2eproto
